name: build and publish container 
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: bump-version-action
      uses: anothrNick/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the order-command docker image
      id: build-command-image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        export TAG_VERSION=$(cat VERSION)
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${TAG_VERSION}
        docker tag ${IMAGE_NAME}:${TAG_VERSION} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        WORKDIR: ${{ repo }}
        DOCKERFILE: Dockerfile.multistage
        IMAGE_NAME: ${{ github.ORG }}/${{ repo }}
        VERSION: ${{ steps.bump-version-action.outputs.new_tag }}
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the order-query docker image
      id: build-query-image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        export TAG_VERSION=$(cat VERSION)
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${TAG_VERSION}
        docker tag ${IMAGE_NAME}:${TAG_VERSION} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
        WORKDIR: ${{ container.WORKDIR }}
        DOCKERFILE: Dockerfile.multistage
        IMAGE_NAME: ${{ github.ORG }}/${{ container.WORKDIR }}
        VERSION: ${{ steps.bump-version-action.outputs.new_tag }}
